<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.5 on linux)" generated="20210618 16:06:47.833" rpa="false" schemaversion="2">
<suite id="s1" name="Mobile-Automation" source="/home/brenoalves/Documentos/Prime-Experts/tests/mobile-automation.robot">
<test id="s1-t1" name="Caso de Teste 01: Abrindo o youtube">
<kw name="Abrir o aplicativo" library="mobile-resource" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<arg>appPackage=com.google.android.youtube</arg>
<arg>appActivity=com.google.android.youtube.HomeActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20210618 16:06:48.636" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20210618 16:06:48.636" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20210618 16:06:48.638" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd370&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.639" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd4c0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.640" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd610&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.676" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.642" endtime="20210618 16:06:48.676"/>
</kw>
<msg timestamp="20210618 16:06:48.677" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.746" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd760&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<status status="FAIL" starttime="20210618 16:06:48.631" endtime="20210618 16:06:48.746"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.631" endtime="20210618 16:06:48.746"/>
</kw>
<kw name="Fechar o aplicativo" library="mobile-resource" type="TEARDOWN">
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.750" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.749" endtime="20210618 16:06:48.750"/>
</kw>
<msg timestamp="20210618 16:06:48.752" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.752" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.748" endtime="20210618 16:06:48.752"/>
</kw>
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.754" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.753" endtime="20210618 16:06:48.754"/>
</kw>
<msg timestamp="20210618 16:06:48.756" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.757" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.753" endtime="20210618 16:06:48.757"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.747" endtime="20210618 16:06:48.757">Several failures occurred:

1) No application is open

2) No application is open</status>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.630" endtime="20210618 16:06:48.758">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd760&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open</status>
</test>
<test id="s1-t2" name="Caso de Teste 02: Logar no YouTube">
<kw name="Abrir o aplicativo" library="mobile-resource" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<arg>appPackage=com.google.android.youtube</arg>
<arg>appActivity=com.google.android.youtube.HomeActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20210618 16:06:48.760" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20210618 16:06:48.760" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20210618 16:06:48.761" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f430&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.762" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f580&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.764" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f6d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.767" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.765" endtime="20210618 16:06:48.767"/>
</kw>
<msg timestamp="20210618 16:06:48.769" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.771" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd1adc0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<status status="FAIL" starttime="20210618 16:06:48.759" endtime="20210618 16:06:48.771"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.759" endtime="20210618 16:06:48.772"/>
</kw>
<kw name="Fechar o aplicativo" library="mobile-resource" type="TEARDOWN">
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.776" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.774" endtime="20210618 16:06:48.776"/>
</kw>
<msg timestamp="20210618 16:06:48.778" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.779" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.773" endtime="20210618 16:06:48.779"/>
</kw>
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.780" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.780" endtime="20210618 16:06:48.781"/>
</kw>
<msg timestamp="20210618 16:06:48.782" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.783" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.779" endtime="20210618 16:06:48.783"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.772" endtime="20210618 16:06:48.783">Several failures occurred:

1) No application is open

2) No application is open</status>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.758" endtime="20210618 16:06:48.783">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd1adc0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open</status>
</test>
<test id="s1-t3" name="Caso de Teste 03: Usar método Swipe na tela">
<kw name="Abrir o aplicativo" library="mobile-resource" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<arg>appPackage=com.google.android.youtube</arg>
<arg>appActivity=com.google.android.youtube.HomeActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20210618 16:06:48.786" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20210618 16:06:48.786" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20210618 16:06:48.787" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33c40&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.788" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33880&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.789" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33550&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.791" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.790" endtime="20210618 16:06:48.791"/>
</kw>
<msg timestamp="20210618 16:06:48.793" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.794" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33130&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<status status="FAIL" starttime="20210618 16:06:48.785" endtime="20210618 16:06:48.794"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.785" endtime="20210618 16:06:48.794"/>
</kw>
<kw name="Fechar o aplicativo" library="mobile-resource" type="TEARDOWN">
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.797" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.796" endtime="20210618 16:06:48.797"/>
</kw>
<msg timestamp="20210618 16:06:48.800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.801" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.795" endtime="20210618 16:06:48.801"/>
</kw>
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210618 16:06:48.802" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.801" endtime="20210618 16:06:48.802"/>
</kw>
<msg timestamp="20210618 16:06:48.804" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.805" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210618 16:06:48.801" endtime="20210618 16:06:48.805"/>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.794" endtime="20210618 16:06:48.805">Several failures occurred:

1) No application is open

2) No application is open</status>
</kw>
<status status="FAIL" starttime="20210618 16:06:48.784" endtime="20210618 16:06:48.805">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33130&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open</status>
</test>
<status status="FAIL" starttime="20210618 16:06:47.834" endtime="20210618 16:06:48.807"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="3" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="3" skip="0" id="s1" name="Mobile-Automation">Mobile-Automation</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210618 16:06:48.638" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd370&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.639" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd4c0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.640" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fdfd610&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.677" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.752" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.756" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.761" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f430&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.762" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f580&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.764" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd2f6d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.769" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.778" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.782" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.787" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33c40&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.788" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33880&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.789" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f768fd33550&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20210618 16:06:48.793" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210618 16:06:48.804" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
